#mybatis:
#  mapper-locations: classpath:mappers/**/*.xml
#  configuration:
#    map-underscore-to-camel-case: true #开启驼峰支持

spring:
  freemarker:
    charset: utf-8
    suffix: .ftl
    content-type: text/html; charset=utf-8
    template-loader-path: classpath:/templates

  datasource:

    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/agritainment?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root

  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/
server:
  port: 80

mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mapper/*.xml


